dropbear: generate host rsa key on first launch
Signed-off-by: Marc Andre Tanner <mat@brain-dump.org>

diff --git a/rootfs-overlay/etc/init.d/dropbear b/rootfs-overlay/etc/init.d/dropbear
--- a/rootfs-overlay/etc/init.d/dropbear
+++ b/rootfs-overlay/etc/init.d/dropbear
@@ -1,8 +1,14 @@
 #!/bin/sh
 
+DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
+
 case "$1" in
     start)
-	dropbear
+	if [ ! -f $DROPBEAR_RSAKEY ]; then 
+		echo "Creating RSA host key."
+		dropbearkey -t rsa -f $DROPBEAR_RSAKEY || echo "Key creation failed."
+	fi
+	dropbear || echo "Starting dropbear failed."
 	;;
     stop)
 	killall dropbear
